locals {
  members = [
    "20jun01",        # urturn
    "24take",         # 24take
    "abap34",         # abap34
    "Aketami23",      # aketami
    "Akira-256",      # Akira_256
    "wakky-alcedo",   # wakky
    "alex3333python", # alex_python
    "alter334",       # Alt--er
    "AlteraKlam",     # Alietty
    "anko9801",       # anko
    "Apple000001",    # Apple
    "AstartetraP",    # Astarte
    "aster34",        # Aster
    "Au294",          # Au2942
    "aya-se",         # aya_se
    "Ayaka-mogumogu", # mogumogu1515
    "ayanakm",        # ayana
    "beferia",        # beferia
    "blancnoir256",   # BN256
    "cobalt1024",     # cobalt
    "comavius",       # comavius
    "cp-20",          # cp20
    "dye8128",        # Dye
    "emura0",         # emura
    "eran1515",       # Eran
    "eyerust",        # michadaniel
    "ErrorSyntax1",   # SyntaxError
    "eyemono-moe",    # d_etteiu8383
    "Futadaruma",     # Futadaruma
    "Galvatron4",     # Nek0yanag1
    # "H1rono",     # H1rono_K admin
    "HARUKA0219",  # HARUKA
    "hatchch",     # Hatch
    "hayatroid",   # hayatroid
    "helgev-traP", # helgev
    "hijiki51",    # hijiki51
    "hinamas2004", # hinamas2004
    "Hueter57",    # Hueter
    "Hyde616",     # Hyde_616
    "iChemy",      # iChemy
    # "ikura-hamu", # ikura-hamu admin
    "Imperi13",         # Imperi
    "inutamago-dogegg", # inutamago_dogegg
    "Irori235",         # irori
    "itt828",           # itt
    "jippo-m",          # jippo
    # "kaitoyama",  # kaitoyama admin
    "Kaki256",         # Pina641
    "kamaboko720",     # Kamaboko
    "kamecha",         # kamecha
    "kanibaku",        # kanibaku8
    "karo1111111",     # karo
    "katsudontech",    # katsudon
    "kavos113",        # Kavos
    "Kein1048596",     # Kein
    "kenken714",       # kenken
    "kisepichu",       # tqk
    "kn-tech",         # koki_10
    "Kuh456",          # Kuh
    "Kuryu025",        # Kuryu
    "Liscome",         # Liscome
    "Luftalian",       # Luftalian
    "Luke256",         # Luke256
    "mathsuky",        # masky5859
    "mehm8128",        # mehm8128
    "miko-misa",       # hacnosuke
    "mirin-mochigome", # mirin
    "mizoreyuki8",     # mizoreyuki
    "motoki317",       # toki
    "mtaku3",          # mtaku3
    "mumumu6",         # mumumu
    "n-kegra",         # kegra
    "nagaeki",         # eki
    "NagatsukiSep",    # Z
    "Nattuki",         # Natsuki
    "nokhnaton",       # noc7t
    "Nors5648",        # Nors5648
    "noya2ruler",      # noya2
    "Nzt3-gh",         # Nzt3
    "oER4",            # o_ER4
    "ogu-kazemiya",    # ogu_kazemiya
    "oribe1115",       # oribe
    "penguin23-001",   # penguin23
    "Pentakon26",      # Pentakon
    "pikachu0310",     # pikachu
    "pippi0057",       # pippi0057
    "pirosiki197",     # pirosiki
    "PL-38",           # PL-38
    "Propromp",        # matsun
    "Pugma",           # Pugma
    "ramdos0207",      # ramdos
    "ras0q",           # Ras
    "reiroop",         # rei
    "riku6174",        # riku_6174
    "Rozelin-dc",      # Rozelin
    "s9-sukyu",        # s9
    "saitenntaisei",   # saiten
    "SakanoYuito",     # shirasu_oisi
    "SakuAs0",         # SakuAs
    "saltbread1",      # take
    "sea314",          # sea314
    "Series-205",      # Series_205
    "sh0go07",         # shogotin
    "shibutomo",       # Mozuya
    "shushuya0210",    # eru_o2lo
    "shota973",        # shota_s
    "Silent-Clubstep", # shunapo
    "Sokugame",        # sokugame
    "soramea",         # soramea
    "Sotatsu57",       # Sotatsu
    "soucy-745",       # soucy
    "SSlime-s",        # SSLime
    "stamtam",         # stam
    "sumirinn",        # sumirin
    "superharuma",     # haruma
    "Synori",          # Synori
    # "Takeno-hito", # Takeno_hito admin
    "taxfree-python", # tax_free
    "the-edible-pan", # the_edible_pan
    "Thunder32768",   # Cd_48
    "tkr-555",        # tkr_d_555
    "tobuhitodesu",   # tobuhitodesu
    "topaz13",        # topaz
    "toshi-pono",     # toshi00
    "trasta298",      # trasta
    "TwoSquirrels",   # TwoSquirrels
    "ultsaza",        # kyomu
    "usomatsu",       # usomatsu
    "uz4ki",          # Uzaki
    "vPhos",          # vPhos
    "Wertsatz",       # Wert
    "YMAC-STICK",     # YMAC
    "ynta-3",         # Hokaze
    "yuchi-cpu",      # u
    "YuHima03",       # tidus
    "Yuki-Ots",       # Umin
    "yukikurage",     # yukikurage
    "zer0-star",      # zer0-star
    "ZOI-dayo"        # zoi_dayo
  ]
}
