locals {
  members = [
    "20jun01",        # urturn
    "24take",         # 24take
    "abap34",         # abap34
    "Aketami23",      # aketami
    "Akira-256",      # Akira_256
    "alter334",       # Alt--er
    "Apple000001",    # Apple
    "aster34",        # Aster
    "ayanakm",        # ayana
    "aya-se",         # aya_se
    "Ayaka-mogumogu", # mogumogu1515
    "beferia",        # beferia
    "cobalt1024",     # cobalt
    "comavius",       # comavius
    "cp-20",          # cp20
    "emura0",         # emura
    "eran1515",       # Eran
    "ErrorSyntax1",   # SyntaxError
    "eyemono-moe",    # d_etteiu8383
    "Galvatron4",     # Nek0yanag1
    # "H1rono",     # H1rono_K admin
    "HARUKA0219",  # HARUKA
    "hayatroid",   # hayatroid
    "helgev-traP", # helgev
    "hijiki51",    # hijiki51
    "hinamas2004", # hinamas2004
    "Hueter57",    # Hueter
    "iChemy",      # iChemy
    # "ikura-hamu", # ikura-hamu admin
    "Imperi13",         # Imperi
    "inutamago-dogegg", # inutamago_dogegg
    "Irori235",         # irori
    "itt828",           # itt
    # "kaitoyama",  # kaitoyama admin
    "Kaki256",       # Pina641
    "kamaboko720",   # Kamaboko
    "kanibaku",      # kanibaku8
    "karo1111111",   # karo
    "Kein1048596",   # Kein
    "kenken714",     # kenken
    "kisepichu",     # tqk
    "Kuryu025",      # Kuryu
    "Liscome",       # Liscome
    "Luftalian",     # Luftalian
    "mathsuky",      # masky5859
    "mehm8128",      # mehm8128
    "miko-misa",     # hacnosuke
    "mizoreyuki8",   # mizoreyuki
    "mtaku3",        # mtaku3
    "n-kegra",       # kegra
    "nagaeki",       # eki
    "NagatsukiSep",  # Z
    "Nors5648",      # Nors5648
    "Nzt3-gh",       # Nzt3
    "oER4",          # o_ER4
    "oribe1115",     # oribe
    "penguin23-001", # penguin23
    "pikachu0310",   # pikachu
    "pirosiki197",   # pirosiki
    "PL-38",         # PL-38
    "Pugma",         # Pugma
    "ramdos0207",    # ramdos
    "ras0q",         # Ras
    "s9-sukyu",      # s9
    "saitenntaisei", # saiten
    "SakanoYuito",   # shirasu_oisi
    "SakuAs0",       # SakuAs
    "saltbread1",    # take
    "sea314",        # sea314
    "sh0go07",       # shogotin
    "Sokugame",      # sokugame
    "soramea",       # soramea
    "Sotatsu57",     # Sotatsu
    "soucy-745",     # soucy
    "SSlime-s",      # SSLime
    "sumirinn",      # sumirin
    "Synori",        # Synori
    # "Takeno-hito", # Takeno_hito admin
    "taxfree-python", # tax_free
    "Thunder32768",   # Cd_48
    "tkr-555",        # tkr_d_555
    "tobuhitodesu",   # tobuhitodesu
    "topaz13",        # topaz
    "toshi-pono",     # toshi00
    "trasta298",      # trasta
    "TwoSquirrels",   # TwoSquirrels
    "usomatsu",       # usomatsu
    "uz4ki",          # Uzaki
    "vPhos",          # vPhos
    "Wertsatz",       # Wert
    "yuchi-cpu",      # u
    "Yuki-Ots",       # Umin
    "yukikurage",     # yukikurage
    "zer0-star",      # zer0-star
    "ZOI-dayo"        # ZOI
  ]
}
